### PR TITLE
FIX: Slapping Animation is now functional.

### PR DESCRIPTION
**Pull request by Blackwolf1337**
Issue #380 has been solved which has been reported by an EFF Player.

### CODE REVIEW

**Comment by Blackwolf1337** [comment]
Sry for the "Merge remote-tracking brach..." Spam, Github Destkop App Herp'aderps a bit.

**Comment by ensiform** [comment]
Avoid that app at all costs.

**Comment by Razish** [comment]
Try to make pull requests from a new branch (not master) and use rebase + squash commits before creating the PR.

I've manually merged this in 21c83e6 :>

**Comment by Blackwolf1337** [comment]
Alright gonna try that.

**Pull request closed without merging**
