### PR TITLE
 Removed saberBlock*

### PR DESCRIPTION
**Pull request by Wookiee-**
japp_saberBlockChanceMin, japp_saberBlockChanceMax , japp_saberBlockChanceScale, japp_saberBlockStanceParity calls removed.

Used OpenJK method for g_combat.cpp, w_saber.cpp (SabercanBlock, SaberBlock).

Still kept the reduced saberblocks with a small fix from loda from japro.

I have tested this on my Dallas JA++ dev server with another coder friend to evaluate these changes

### CODE REVIEW

**Comment by Blackwolf1337** [comment]
I talked about this with @Razish and you shouldn't touch that part of code.
Also what OpenJK Fixes??? Can you please link them.

**Comment by Razish** [comment]
This removes the slept or ghosted playing ignoring saber collisions.
There are no "OJK fixes". After comparing the JA++ file before and after this commit, the only effective change is within the `japp_saberTweaks.integer & SABERTWEAK_REDUCEBLOCKS` segment and the ghosted/slept player changes. The rest is just style changes.

It would be better to still allow these options, but the server owner should balance them more toward what this commit achieves.
[This](https://thejawaclan.com/topic/36505-/?page=14#comment-376309) post describes the effects.

**Comment by Wookiee-** [comment]
Sorry I had no idea there was a thread on the JAWA forums concerning this.

**Comment by Blackwolf1337** [comment]
@Wookiee- 
Sorry about that I think, I misspelled myself. Well didn't knew that you posted on JKHub forums also. At the first commit it looked like you removed a lot of code.

**Comment by Wookiee-** [comment]
No worries

**Pull request closed without merging**
